### ISSUE TITLE
When a test is skipped, the start time produced is datetime.min

### ISSUE THREAD

**Issue by vtbassmatt** [xmlrunner/unittest-xml-reporting#168] opened 2018-07-12 14:30 UTC
When a test is skipped, the output XML contains a startDate of `datetime.datetime.min`. This confuses the TFS/VSTS test results uploader (and possibly other tools). https://github.com/nunit/nunit/issues/2339 suggests that they're going to start generating start/stop times of datetime.now. 

Could a corresponding change be made here? I'd open a PR but I wasn't clear where this should go. Maybe [here](https://github.com/xmlrunner/unittest-xml-reporting/blob/79621f34497f7e41fb36e9c932d7258f9c5d9175/xmlrunner/result.py#L139) ?

**Comment by kieseld** [comment] 2018-08-20 16:18
https://developercommunity.visualstudio.com/content/problem/196633/tfs-2018-failed-to-publish-test-results-the-value.html

Looks like VS 15.8 was supposed to fix it but the issue is still there.

**Comment by dnozay** [comment] 2019-03-14 01:39
> https://developercommunity.visualstudio.com/content/problem/196633/tfs-2018-failed-to-publish-test-results-the-value.html

@kieseld, @vtbassmatt 
Looks fixed: https://github.com/Microsoft/azure-pipelines-agent/releases/tag/v2.140.2

I am going to close this.

**Closed by dnozay** 2019-03-14 01:39 UTC
